"""Shared rendering helpers for the workflow session management interface."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/components/helpers.ipynb.

# %% auto #0
__all__ = ['DEBUG_SESSION_RENDER', 'render_section_header', 'render_icon_button', 'render_alert', 'render_delete_modal',
           'render_empty_state', 'render_active_session_badge']

# %% ../../nbs/components/helpers.ipynb #82d4c88f
from typing import Any, Dict, List, Optional

from fasthtml.common import Div, Span, H3, Button, Form, P, Dialog, Input

# DaisyUI components
# btn / btn_styles / btn_colors / btn_sizes still used by `render_icon_button`
# (a row-action helper that pre-dates V1 and represents a V1 catalog gap for
# row-action icon buttons). Other sites in this file use V1 buttons directly.
from cjm_fasthtml_daisyui.components.actions.button import (
    btn, btn_colors, btn_styles, btn_sizes
)
from cjm_fasthtml_daisyui.components.data_display.badge import (
    badge, badge_colors, badge_styles, badge_sizes
)
from cjm_fasthtml_daisyui.components.feedback.alert import alert, alert_colors
from cjm_fasthtml_daisyui.components.actions.modal import (
    modal, modal_box, modal_action, modal_backdrop
)
from cjm_fasthtml_daisyui.utilities.semantic_colors import text_dui

# Tailwind utilities
from cjm_fasthtml_tailwind.utilities.spacing import p, m
from cjm_fasthtml_tailwind.utilities.typography import font_size, font_weight, text_align
from cjm_fasthtml_tailwind.utilities.flexbox_and_grid import (
    flex_display, flex_direction, items, justify, gap
)
from cjm_fasthtml_tailwind.core.base import combine_classes

# Icons
from cjm_fasthtml_lucide_icons.factory import lucide_icon

# Design system recipes (V1 button roles, V11 icon-size roles)
from cjm_fasthtml_design_system.buttons import buttons
from cjm_fasthtml_design_system.icons import icons

# %% ../../nbs/components/helpers.ipynb #504a685b
DEBUG_SESSION_RENDER = False # Enable for verbose component rendering logs

# %% ../../nbs/components/helpers.ipynb #43815fa4
def render_section_header(
    title:str, # Section title text
    icon_name:str, # Lucide icon name (kebab-case)
) -> Any: # Header element with icon and title
    """Render a section header with a leading lucide icon."""
    return H3(
        lucide_icon(icon_name, size=icons.section_header),
        title,
        cls=combine_classes(
            font_size.lg, font_weight.semibold,
            flex_display, items.center, gap(2)
        )
    )

# %% ../../nbs/components/helpers.ipynb #a65b1e32
def render_icon_button(
    icon_name:str, # Lucide icon name (kebab-case)
    label:str, # Accessible tooltip label
    color:Optional[str]=None, # DaisyUI button color class (e.g. btn_colors.error)
    size:Optional[str]=None, # DaisyUI button size class (e.g. btn_sizes.sm)
    **kwargs # Additional HTML attributes (hx_post, onclick, etc.)
) -> Any: # Button element with icon
    """Render a ghost-style button with an icon and accessible label.
    
    Defaults to `type="button"` to prevent accidental form submission when
    rendered inside a wrapping form. Callers can override by passing `type=...`.
    """
    classes = [btn, btn_styles.ghost]
    if color: classes.append(color)
    if size: classes.append(size)
    kwargs.setdefault("type", "button")
    return Button(
        lucide_icon(icon_name, size=icons.icon_button),
        title=label,
        cls=combine_classes(*classes),
        **kwargs
    )

# %% ../../nbs/components/helpers.ipynb #f5a88b2e
def render_alert(
    message:str, # Alert message text
    color:Optional[str]=None, # DaisyUI alert color class (e.g. alert_colors.success)
    alert_id:str="", # Optional HTML ID for the alert
) -> Any: # Alert element
    """Render a DaisyUI alert message."""
    classes = [alert]
    if color: classes.append(color)
    kwargs = {"role": "alert", "cls": combine_classes(*classes)}
    if alert_id: kwargs["id"] = alert_id
    return Div(Span(message), **kwargs)

# %% ../../nbs/components/helpers.ipynb #ed3b6ba4
def render_delete_modal(
    modal_id:str, # HTML ID for the dialog element
    body_id:str, # HTML ID for the modal body (HTMX target for confirmation text)
    title:str="Delete Session?", # Modal title text
    confirm_attrs:Optional[Dict[str, Any]]=None, # Attributes for the confirm button (hx_post, etc.)
) -> Any: # Dialog element
    """Render a delete confirmation modal using HTML5 dialog with backdrop click-to-close."""
    confirm_attrs = confirm_attrs or {}
    # Ensure the confirm button is never treated as a form submit button.
    confirm_attrs.setdefault("type", "button")
    return Dialog(
        Div(
            H3(title, cls=combine_classes(font_size.lg, font_weight.bold)),
            Div(id=body_id, cls=m.y(4)),
            Div(
                Form(
                    Button("Cancel", cls=buttons.soft_dismissal, formmethod="dialog"),
                    method="dialog",
                ),
                Button(
                    lucide_icon("trash-2", size=icons.text_button),
                    "Delete",
                    cls=combine_classes(
                        buttons.destructive_confirm,
                        flex_display, items.center, gap(1)
                    ),
                    **confirm_attrs,
                ),
                cls=combine_classes(modal_action, flex_display, gap(2)),
            ),
            cls=str(modal_box),
        ),
        # Backdrop — plain unstyled button per DaisyUI v5 pattern. Clicking
        # anywhere outside the modal_box submits this form (method="dialog")
        # which closes the dialog natively.
        Form(Button("close"), method="dialog", cls=str(modal_backdrop)),
        id=modal_id,
        cls=str(modal),
    )

# %% ../../nbs/components/helpers.ipynb #1811e4cb
def render_empty_state(
    message:str="No sessions found.", # Primary message
    detail:str="Start a new session to begin a workflow.", # Secondary detail
) -> Any: # Empty state element
    """Render an empty state placeholder with an icon and two lines of copy."""
    return Div(
        lucide_icon("inbox", size=icons.empty_state, cls=str(text_dui.base_content.opacity(30))),
        P(message, cls=combine_classes(
            font_size.lg, font_weight.medium, m.t(4)
        )),
        P(detail, cls=combine_classes(
            font_size.sm, text_dui.base_content.opacity(60)
        )),
        cls=combine_classes(
            flex_display, flex_direction.col, items.center, justify.center,
            text_align.center, p(12)
        )
    )

# %% ../../nbs/components/helpers.ipynb #07e8ab15
def render_active_session_badge(
    label:str="Active", # Badge label text
    badge_id:str="", # Optional HTML ID for the badge
) -> Any: # Span element containing the badge
    """Render the "Active" indicator badge for the currently active session row."""
    kwargs = {
        "cls": combine_classes(
            badge, badge_colors.success, badge_sizes.sm,
            flex_display, items.center, gap(1)
        )
    }
    if badge_id: kwargs["id"] = badge_id
    return Span(
        lucide_icon("circle-dot", size=icons.dense_inline),
        label,
        **kwargs
    )
