"""Full session management page assembly — header with title and the session list body."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/components/page_renderer.ipynb.

# %% auto #0
__all__ = ['render_page_header', 'render_session_manager_page']

# %% ../../nbs/components/page_renderer.ipynb #e5116bf4
from typing import Any, Callable, Optional

from fasthtml.common import Div, H1

from cjm_fasthtml_tailwind.utilities.spacing import p, m
from cjm_fasthtml_tailwind.utilities.sizing import container, max_w, h
from cjm_fasthtml_tailwind.utilities.typography import font_size, font_weight
from cjm_fasthtml_tailwind.utilities.flexbox_and_grid import (
    flex_display, flex_direction, items, gap,
)
from cjm_fasthtml_tailwind.core.base import combine_classes

from cjm_fasthtml_lucide_icons.factory import lucide_icon

from ..models import SessionManagementUrls
from ..html_ids import SessionManagerHtmlIds
from .helpers import DEBUG_SESSION_RENDER

# %% ../../nbs/components/page_renderer.ipynb #bb87371d
def render_page_header(
    title:str="Sessions", # Page title
    icon_name:str="layers", # Lucide icon for the title
) -> Any: # Header element
    """Render the page header with an icon + title."""
    return Div(
        H1(
            lucide_icon(icon_name, size=7),
            title,
            cls=combine_classes(
                font_size._3xl, font_weight.bold,
                flex_display, items.center, gap(3),
            ),
        ),
        cls=combine_classes(flex_display, flex_direction.col, m.b(4)),
    )

# %% ../../nbs/components/page_renderer.ipynb #a0a55522
def render_session_manager_page(
    urls:SessionManagementUrls, # URL bundle (unused directly, reserved for future header actions)
    render_list_fn:Callable, # () -> session list component
    title:str="Sessions", # Page title
    icon_name:str="layers", # Lucide icon name for the title
) -> Any: # Complete session manager page component
    """Render the complete session manager page with header and session list."""
    if DEBUG_SESSION_RENDER:
        print(f"[RENDER] session_manager_page")
    return Div(
        render_page_header(title=title, icon_name=icon_name),
        render_list_fn(),
        id=SessionManagerHtmlIds.PAGE_CONTENT,
        cls=combine_classes(
            container, max_w._5xl, m.x.auto,
            flex_display, flex_direction.col,
            p(4), gap(4), h.full,
        ),
    )
