"""Session list component with virtual collection integration, keyboard navigation, and action modals."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/components/session_list.ipynb.

# %% auto #0
__all__ = ['build_session_columns', 'create_session_cell_renderer', 'render_session_toolbar', 'render_rename_modal',
           'render_list_scripts', 'render_session_list']

# %% ../../nbs/components/session_list.ipynb #80d670ec
from typing import Any, Callable, List, Optional

from fasthtml.common import Div, Span, A, Button, Input, Label, Script, H3, Form, Dialog, P

# DaisyUI components
# btn_colors / btn_sizes still used as params passed to render_icon_button
# (a row-action helper that pre-dates V1 and represents a V1 catalog gap for
# row-action icon buttons). Other sites in this file use V1 buttons directly.
from cjm_fasthtml_daisyui.components.actions.button import (
    btn_colors, btn_sizes
)
from cjm_fasthtml_daisyui.components.data_input.text_input import text_input
from cjm_fasthtml_daisyui.components.actions.modal import (
    modal, modal_box, modal_action, modal_backdrop,
)
from cjm_fasthtml_daisyui.utilities.semantic_colors import text_dui

# Tailwind utilities
from cjm_fasthtml_tailwind.utilities.spacing import p, m
from cjm_fasthtml_tailwind.utilities.sizing import w, min_h
from cjm_fasthtml_tailwind.utilities.typography import font_size, font_weight
from cjm_fasthtml_tailwind.utilities.layout import overflow
from cjm_fasthtml_tailwind.utilities.flexbox_and_grid import (
    flex_display, flex_direction, items, justify, gap, grow
)
from cjm_fasthtml_tailwind.core.base import combine_classes

# Icons
from cjm_fasthtml_lucide_icons.factory import lucide_icon

# Design system recipes (V1 button roles, V11 icon-size roles)
from cjm_fasthtml_design_system.buttons import buttons
from cjm_fasthtml_design_system.icons import icons

# App core: V12 confirm-modal recipe
from cjm_fasthtml_app_core.components.confirm_modal import render_confirm_modal

# Virtual collection
from cjm_fasthtml_virtual_collection.core.models import (
    VirtualCollectionConfig, VirtualCollectionState, ColumnDef, CellRenderContext,
    VirtualCollectionUrls,
)
from cjm_fasthtml_virtual_collection.core.html_ids import VirtualCollectionHtmlIds
from cjm_fasthtml_virtual_collection.core.button_ids import VirtualCollectionButtonIds
from cjm_fasthtml_virtual_collection.components.collection import render_virtual_collection

# Keyboard navigation
from cjm_fasthtml_keyboard_navigation.components.system import render_keyboard_system
from cjm_fasthtml_keyboard_navigation.core.manager import ZoneManager
from cjm_fasthtml_virtual_collection.keyboard.actions import (
    create_collection_focus_zone,
    create_collection_nav_actions,
    build_collection_url_map,
    apply_nav_sync,
)

# JS generators
from cjm_fasthtml_virtual_collection.js.scroll import generate_scroll_nav_js
from cjm_fasthtml_virtual_collection.js.scrollbar import generate_scrollbar_js
from cjm_fasthtml_virtual_collection.js.auto_fit import generate_auto_fit_js, auto_fit_callback_name

# Viewport fit
from cjm_fasthtml_viewport_fit.models import ViewportFitConfig
from cjm_fasthtml_viewport_fit.components import render_viewport_fit_script

# Local
from cjm_fasthtml_workflow_session_management.models import (
    EnrichedSessionSummary, SessionManagementUrls, ColumnSpec,
)
from ..html_ids import SessionManagerHtmlIds
from ..utils import format_relative_time, format_bytes
from cjm_fasthtml_workflow_session_management.components.helpers import (
    render_icon_button, render_empty_state,
    render_active_session_badge, DEBUG_SESSION_RENDER,
)

# %% ../../nbs/components/session_list.ipynb #41433ba7
def build_session_columns(
    column_specs:Optional[List[ColumnSpec]]=None, # Host-supplied enricher column specs
) -> tuple: # Tuple of ColumnDef for the VC config
    """Build the column definitions for the session list.
    
    Produces a fixed column layout with host enricher columns inserted between
    status and updated columns. If `column_specs` is None or empty, only fixed
    columns are included.
    """
    specs = column_specs or []
    cols = [
        ColumnDef(key="label", header="Session", sortable=True),
        ColumnDef(key="status", header="Step", sortable=True),
    ]
    for spec in specs:
        cols.append(ColumnDef(
            key=spec.field,
            header=spec.header,
            sortable=False,
            header_cls=spec.width_class or "",
            cell_cls=spec.width_class or "",
        ))
    cols.extend([
        ColumnDef(key="updated", header="Updated", sortable=True),
        ColumnDef(key="size", header="Size", sortable=False),
        ColumnDef(key="actions", header="", sortable=False, header_cls=str(w("40"))),
    ])
    return tuple(cols)

# %% ../../nbs/components/session_list.ipynb #5dc57180
def create_session_cell_renderer(
    urls:SessionManagementUrls, # URL bundle for action buttons
    get_active_session_id:Callable[[], str], # () -> currently active session ID
    get_step_title:Optional[Callable[[str], str]]=None, # Optional step ID -> human title mapper
) -> Callable: # render_cell(item, ctx) -> FT component
    """Create a cell renderer for the session list virtual collection."""
    def render_cell(
        item:EnrichedSessionSummary, # Enriched session at this row
        ctx:CellRenderContext, # Context with row_index, column, etc.
    ) -> Any: # FT component for the cell
        key = ctx.column.key
        sid = item.summary.session_id
        
        if key == "label":
            children = [Span(item.resolved_label, cls=str(font_weight.medium))]
            if sid == get_active_session_id():
                children.append(render_active_session_badge())
            return Div(*children, cls=combine_classes(flex_display, items.center, gap(2)))
        
        if key == "status":
            step_id = item.summary.current_step or ""
            title = get_step_title(step_id) if get_step_title and step_id else step_id
            return Span(title or "—", cls=str(font_size.sm))
        
        if key == "updated":
            return Span(
                format_relative_time(item.summary.updated_at),
                title=item.summary.updated_at or "",
                cls=str(font_size.sm),
            )
        
        if key == "size":
            return Span(format_bytes(item.summary.state_size_bytes), cls=str(font_size.sm))
        
        if key == "actions":
            safe_label = (item.resolved_label or "").replace("'", "\\'").replace('"', '\\"')
            return Div(
                render_icon_button(
                    "circle-play", "Resume",
                    size=str(btn_sizes.sm),
                    hx_post=urls.resume_session,
                    hx_vals=f'{{"session_id": "{sid}"}}',
                    hx_swap="none",
                    onclick="event.stopPropagation()",
                ),
                render_icon_button(
                    "square-pen", "Rename",
                    size=str(btn_sizes.sm),
                    onclick=(
                        f"event.stopPropagation(); "
                        f"prepareRenameModal('{sid}', '{safe_label}'); "
                        f"document.getElementById('{SessionManagerHtmlIds.RENAME_MODAL}').showModal()"
                    ),
                ),
                render_icon_button(
                    "trash-2", "Delete",
                    color=str(btn_colors.error),
                    size=str(btn_sizes.sm),
                    onclick=(
                        f"event.stopPropagation(); "
                        f"prepareDeleteModal('{sid}', '{safe_label}'); "
                        f"document.getElementById('{SessionManagerHtmlIds.DELETE_MODAL}').showModal()"
                    ),
                ),
                cls=combine_classes(flex_display, gap(1)),
            )
        
        # Fallback: enricher-backed column.
        value = item.enriched_fields.get(key, "—")
        return Span(value, cls=str(font_size.sm))
    
    return render_cell

# %% ../../nbs/components/session_list.ipynb #32f2a9e8
def render_session_toolbar(
    urls:SessionManagementUrls, # URL bundle for action routes
    total_count:int=0, # Total number of sessions in the list
) -> Any: # Toolbar element
    """Render the session list toolbar with session count and New Session button."""
    count_label = "1 session" if total_count == 1 else f"{total_count} sessions"
    return Div(
        # Left: session count
        Span(
            count_label,
            cls=combine_classes(font_size.sm, text_dui.base_content.opacity(70)),
        ),
        # Right: New Session button
        Button(
            lucide_icon("plus", size=icons.text_button),
            "New Session",
            type="button",  # Prevent form-submit hijack inside any wrapping form.
            cls=combine_classes(
                buttons.primary_action,
                flex_display, items.center, gap(1),
            ),
            id=SessionManagerHtmlIds.NEW_SESSION_BTN,
            hx_post=urls.create_session,
            hx_swap="none",
        ),
        id=SessionManagerHtmlIds.TOOLBAR,
        cls=combine_classes(flex_display, justify.between, items.center, m.b(2)),
    )

# %% ../../nbs/components/session_list.ipynb #071ff77c
def render_rename_modal(
    urls:SessionManagementUrls, # URL bundle for rename route
    modal_id:str=SessionManagerHtmlIds.RENAME_MODAL, # Dialog element ID
    input_id:str=SessionManagerHtmlIds.RENAME_INPUT, # Input element ID
) -> Any: # Dialog element
    """Render the rename session modal using HTML5 dialog with backdrop click-to-close."""
    return Dialog(
        Div(
            H3("Rename Session", cls=combine_classes(font_size.lg, font_weight.bold)),
            Div(
                Input(
                    type="text",
                    id=input_id,
                    name="label",
                    placeholder="Session label",
                    cls=combine_classes(text_input, w.full),
                ),
                cls=m.y(4),
            ),
            Div(
                Form(
                    Button("Cancel", cls=buttons.soft_dismissal, formmethod="dialog"),
                    method="dialog",
                ),
                Button(
                    lucide_icon("check", size=icons.text_button),
                    "Rename",
                    type="button",  # Prevent form-submit hijack inside any wrapping form.
                    cls=combine_classes(
                        buttons.primary_action,
                        flex_display, items.center, gap(1),
                    ),
                    data_rename_confirm="true",
                    hx_post=urls.rename_session,
                    hx_swap="none",
                    onclick=f"document.getElementById('{modal_id}').close()",
                ),
                cls=combine_classes(modal_action, flex_display, gap(2)),
            ),
            cls=str(modal_box),
        ),
        # Backdrop — plain unstyled button per DaisyUI v5 pattern. Clicking
        # anywhere outside the modal_box submits this form (method="dialog")
        # which closes the dialog natively.
        Form(Button("close"), method="dialog", cls=str(modal_backdrop)),
        id=modal_id,
        cls=str(modal),
    )

# %% ../../nbs/components/session_list.ipynb #c720d361
def render_list_scripts(
    urls:SessionManagementUrls, # URL bundle for action routes
) -> Any: # Script element
    """Render client-side JavaScript for delete and rename modal management."""
    faded = combine_classes(font_size.sm, text_dui.base_content.opacity(60), m.t(2))
    return Script(f"""
    function prepareDeleteModal(sessionId, label) {{
        var body = document.getElementById('{SessionManagerHtmlIds.DELETE_MODAL_BODY}');
        if (body) {{
            body.innerHTML = '<p>Permanently delete session "' + label + '"?</p>'
                + '<p class="{faded}">This clears all progress for this session. This action cannot be undone.</p>';
        }}
        var confirmBtn = document.querySelector('#{SessionManagerHtmlIds.DELETE_MODAL} [data-delete-confirm]');
        if (confirmBtn) {{
            confirmBtn.setAttribute('hx-post', '{urls.delete_session}');
            confirmBtn.setAttribute('hx-vals', JSON.stringify({{session_id: sessionId}}));
            confirmBtn.setAttribute('hx-swap', 'none');
            htmx.process(confirmBtn);
        }}
    }}

    function prepareRenameModal(sessionId, currentLabel) {{
        var input = document.getElementById('{SessionManagerHtmlIds.RENAME_INPUT}');
        if (input) {{
            input.value = currentLabel || '';
            setTimeout(function() {{ input.focus(); input.select(); }}, 50);
        }}
        var confirmBtn = document.querySelector('#{SessionManagerHtmlIds.RENAME_MODAL} [data-rename-confirm]');
        if (confirmBtn) {{
            // The label is read from the input on click via hx-include; session_id travels via hx-vals.
            confirmBtn.setAttribute('hx-vals', 'js:{{session_id: "' + sessionId + '", label: document.getElementById("{SessionManagerHtmlIds.RENAME_INPUT}").value}}');
            htmx.process(confirmBtn);
        }}
    }}
    """)

# %% ../../nbs/components/session_list.ipynb #88749920
def render_session_list(
    items:list, # Current session list (List[EnrichedSessionSummary])
    vc_config:VirtualCollectionConfig, # VC configuration
    vc_state:VirtualCollectionState, # VC state
    vc_ids:VirtualCollectionHtmlIds, # VC HTML IDs
    vc_btn_ids:VirtualCollectionButtonIds, # VC button IDs
    vc_urls:VirtualCollectionUrls, # VC route URLs
    mgmt_urls:SessionManagementUrls, # Session manager URLs
    render_cell:Callable, # Cell renderer callback
) -> Any: # Complete session list component
    """Render the session list with virtual collection, keyboard nav, and modals."""
    if DEBUG_SESSION_RENDER:
        print(f"[RENDER] session_list: {len(items)} sessions")
    
    # Empty state short-circuit.
    if not items:
        return Div(
            render_session_toolbar(mgmt_urls, total_count=0),
            render_empty_state(
                message="No sessions found.",
                detail="Click New Session to start your first workflow.",
            ),
            # Persistent scripts + modals so toolbar's New Session still works.
            render_list_scripts(mgmt_urls),
            render_confirm_modal(
                modal_id=SessionManagerHtmlIds.DELETE_MODAL,
                body_id=SessionManagerHtmlIds.DELETE_MODAL_BODY,
                title="Delete Session?",
                confirm_label="Delete",
                confirm_icon="trash-2",
                confirm_attrs={
                    "data_delete_confirm": "true",
                    "onclick": f"document.getElementById('{SessionManagerHtmlIds.DELETE_MODAL}').close()",
                },
            ),
            render_rename_modal(mgmt_urls),
            id=SessionManagerHtmlIds.SESSION_LIST,
            cls=combine_classes(flex_display, flex_direction.col, grow(1), min_h(0)),
        )
    
    # Keyboard system.
    zone = create_collection_focus_zone(vc_ids)
    nav_actions = create_collection_nav_actions(zone.id, vc_btn_ids)
    manager = ZoneManager(zones=(zone,), actions=nav_actions)
    url_map = build_collection_url_map(vc_btn_ids, vc_urls)
    target_map = {btn_id: f"#{vc_ids.rows}" for btn_id in url_map}
    swap_map = {btn_id: "none" for btn_id in url_map}
    kb_system = render_keyboard_system(
        manager,
        url_map=url_map,
        target_map=target_map,
        swap_map=swap_map,
    )
    apply_nav_sync(kb_system, vc_ids)
    
    # Viewport fit for auto-sizing.
    vf_config = ViewportFitConfig(
        namespace=vc_config.prefix,
        target_id=vc_ids.wrapper,
        resize_callback=auto_fit_callback_name(vc_config),
        enable_htmx_settle=False,
    )
    
    # JavaScript for VC navigation.
    js_code = "\n".join([
        generate_scroll_nav_js(vc_ids, vc_btn_ids),
        generate_scrollbar_js(vc_ids, vc_urls),
        generate_auto_fit_js(vc_ids, vc_config, vc_urls, total_items=len(items)),
    ])
    
    return Div(
        render_session_toolbar(mgmt_urls, total_count=len(items)),
        Div(
            render_virtual_collection(
                items=items,
                config=vc_config,
                state=vc_state,
                ids=vc_ids,
                urls=vc_urls,
                render_cell=render_cell,
                render_empty=lambda: render_empty_state(
                    message="No sessions found.",
                    detail="Click New Session to start your first workflow.",
                ),
            ),
            cls=combine_classes(
                flex_display, flex_direction.col, grow(1), min_h(0), overflow.hidden,
            ),
        ),
        Div(id=SessionManagerHtmlIds.ALERT_AREA),
        render_confirm_modal(
            modal_id=SessionManagerHtmlIds.DELETE_MODAL,
            body_id=SessionManagerHtmlIds.DELETE_MODAL_BODY,
            title="Delete Session?",
            confirm_label="Delete",
            confirm_icon="trash-2",
            confirm_attrs={
                "data_delete_confirm": "true",
                "onclick": f"document.getElementById('{SessionManagerHtmlIds.DELETE_MODAL}').close()",
            },
        ),
        render_rename_modal(mgmt_urls),
        kb_system.script,
        kb_system.hidden_inputs,
        kb_system.action_buttons,
        render_list_scripts(mgmt_urls),
        Script(js_code),
        render_viewport_fit_script(vf_config),
        id=SessionManagerHtmlIds.SESSION_LIST,
        cls=combine_classes(flex_display, flex_direction.col, grow(1), min_h(0)),
    )
