"""HTML ID constants for the workflow session management interface"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/html_ids.ipynb.

# %% auto #0
__all__ = ['SessionManagerHtmlIds']

# %% ../nbs/html_ids.ipynb #b5f77afd
# Framework-agnostic — no external imports needed.

class SessionManagerHtmlIds:
    """HTML ID constants for the workflow session management interface."""

    @staticmethod
    def as_selector(
        id_str:str # The HTML ID to convert
    ) -> str: # CSS selector with # prefix
        """Convert an ID to a CSS selector format."""
        return f"#{id_str}"

    # Virtual collection prefix (underscores — used in JS callback names).
    VC_PREFIX = "wsm_sess"

    # Page sections
    PAGE_CONTENT = "wsm-page-content"
    SESSION_LIST = "wsm-session-list"
    SESSION_DETAIL = "wsm-session-detail"

    # Toolbar
    TOOLBAR = "wsm-toolbar"
    NEW_SESSION_BTN = "wsm-new-session-btn"
    RESUME_BTN = "wsm-resume-btn"
    RENAME_BTN = "wsm-rename-btn"
    DELETE_BTN = "wsm-delete-btn"

    # Modals
    DELETE_MODAL = "wsm-delete-modal"
    DELETE_MODAL_BODY = "wsm-delete-modal-body"
    RENAME_MODAL = "wsm-rename-modal"
    RENAME_MODAL_BODY = "wsm-rename-modal-body"
    RENAME_INPUT = "wsm-rename-input"

    # Feedback
    ALERT_AREA = "wsm-alert-area"

    # Badges
    ACTIVE_SESSION_BADGE = "wsm-active-session-badge"
