"""Data models for the workflow session management interface"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/models.ipynb.

# %% auto #0
__all__ = ['SessionEnricher', 'LabelGenerator', 'EnrichedSessionSummary', 'ColumnSpec', 'SessionManagementUrls',
           'SessionManagementResult']

# %% ../nbs/models.ipynb #a7b21632
from dataclasses import dataclass, field
from typing import Any, Callable, Dict, List, Optional

from cjm_workflow_state.state_store import SessionSummary

# %% ../nbs/models.ipynb #190431bb
# Host-supplied: turn a raw state_json blob into a dict of display strings.
# Keys become column field names; values are already-formatted display strings.
SessionEnricher = Callable[[Dict[str, Any]], Dict[str, str]]

# Host-supplied: derive a human-readable label from a SessionSummary + raw state blob.
# Called only when summary.label is None.
LabelGenerator = Callable[[SessionSummary, Dict[str, Any]], str]

# %% ../nbs/models.ipynb #5c43fc04
@dataclass
class EnrichedSessionSummary:
    """Session metadata plus resolved label and host-enriched display fields."""
    summary: SessionSummary # Raw session metadata from cjm-workflow-state
    resolved_label: str # summary.label if set, else label_generator output, else a default
    enriched_fields: Dict[str, str] = field(default_factory=dict) # Host enricher output — keyed by column field name

# %% ../nbs/models.ipynb #6e9a7dc2
@dataclass
class ColumnSpec:
    """Declarative spec for a single enricher-backed column in the session list."""
    field: str # Key into EnrichedSessionSummary.enriched_fields
    header: str # Human-readable column header
    width_class: Optional[str] = None # Optional tailwind width class (e.g., "w-24") for the column

# %% ../nbs/models.ipynb #1690f910
@dataclass
class SessionManagementUrls:
    """URL bundle for session management route endpoints."""
    management_page: str # GET: full session manager page
    list_sessions: str # GET: session list fragment (for OOB refresh)
    session_detail: str # GET: + ?session_id=... for detail view
    create_session: str # POST: mint a new session and switch to it
    delete_session: str # POST: + session_id in form data
    rename_session: str # POST: + session_id and new label
    resume_session: str # POST: set_session_id + redirect to workflow_url

# %% ../nbs/models.ipynb #0ca47349
@dataclass
class SessionManagementResult:
    """Result of session manager router initialization."""
    routers: List[Any] # APIRouter instances to register
    urls: SessionManagementUrls # URL bundle for route endpoints
    routes: Dict[str, Callable] # Route handler functions keyed by name
    render_page: Callable # () -> full session manager page component
    render_list: Callable # () -> session list component
    refresh_items: Callable # async () -> refresh items from the service
    resume_session: Callable[[Any, str], None] # (sess, session_id) -> set active session ID in the HTTP session
