"""Formatting utilities for the session management interface"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/utils.ipynb.

# %% auto #0
__all__ = ['parse_sqlite_timestamp', 'format_relative_time', 'format_absolute_datetime', 'format_bytes', 'default_label']

# %% ../nbs/utils.ipynb #723cff80
from datetime import datetime, timezone
from typing import Optional

# %% ../nbs/utils.ipynb #b9ee656c
def parse_sqlite_timestamp(
    ts:Optional[str] # ISO timestamp string from SQLite, e.g. "2026-04-08 19:11:50"
) -> Optional[datetime]: # Parsed UTC datetime, or None on failure
    """Parse a SQLite CURRENT_TIMESTAMP string into a timezone-aware UTC datetime."""
    if not ts:
        return None
    try:
        dt = datetime.strptime(ts, "%Y-%m-%d %H:%M:%S")
        return dt.replace(tzinfo=timezone.utc)
    except (ValueError, TypeError):
        return None

# %% ../nbs/utils.ipynb #2ebc5c71
def format_relative_time(
    ts:Optional[str], # SQLite ISO timestamp string
    now:Optional[datetime]=None # Reference "now" for testing; defaults to real now in UTC
) -> str: # Short human-readable relative time
    """Format a SQLite timestamp as a relative time string like "2 hours ago"."""
    dt = parse_sqlite_timestamp(ts)
    if dt is None:
        return "—"
    reference = now if now is not None else datetime.now(timezone.utc)
    delta = reference - dt
    seconds = int(delta.total_seconds())
    if seconds < 0:
        return "in the future"
    if seconds < 60:
        return "just now"
    if seconds < 3600:
        minutes = seconds // 60
        return f"{minutes} minute{'s' if minutes != 1 else ''} ago"
    if seconds < 86400:
        hours = seconds // 3600
        return f"{hours} hour{'s' if hours != 1 else ''} ago"
    if seconds < 172800:
        return "yesterday"
    if seconds < 604800:
        days = seconds // 86400
        return f"{days} days ago"
    if seconds < 2592000:  # ~30 days
        weeks = seconds // 604800
        return f"{weeks} week{'s' if weeks != 1 else ''} ago"
    # Fallback: absolute date for anything older than a month.
    return dt.strftime("%b %d, %Y")

# %% ../nbs/utils.ipynb #524fa047
def format_absolute_datetime(
    ts:Optional[str] # SQLite ISO timestamp string
) -> str: # Formatted datetime, e.g. "Apr 08, 2026 19:11"
    """Format a SQLite timestamp as an absolute human-readable datetime."""
    dt = parse_sqlite_timestamp(ts)
    if dt is None:
        return "—"
    return dt.strftime("%b %d, %Y %H:%M")

# %% ../nbs/utils.ipynb #d5e314b8
def format_bytes(
    n:Optional[int] # Size in bytes
) -> str: # Compact human-readable size, e.g. "1.2 KB"
    """Format a byte count as a compact human-readable size."""
    if n is None or n < 0:
        return "—"
    if n < 1024:
        return f"{n} B"
    if n < 1024 * 1024:
        return f"{n / 1024:.1f} KB"
    return f"{n / (1024 * 1024):.1f} MB"

# %% ../nbs/utils.ipynb #7dfbcb85
def default_label(
    created_at:Optional[str] # SQLite ISO timestamp of session creation
) -> str: # Fallback label, e.g. "Session 2026-04-08 19:11"
    """Produce a fallback session label based on creation time."""
    dt = parse_sqlite_timestamp(created_at)
    if dt is None:
        return "Untitled Session"
    return f"Session {dt.strftime('%Y-%m-%d %H:%M')}"
