"""Service layer wrapping `cjm-workflow-state` for session management operations"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/services/management.ipynb.

# %% auto #0
__all__ = ['DEBUG_SESSION_SERVICE', 'SessionManagementService']

# %% ../../nbs/services/management.ipynb #9c70a611
from typing import Any, Dict, List, Optional

from fastcore.basics import patch

from cjm_workflow_state.state_store import SQLiteWorkflowStateStore, SessionSummary

from cjm_fasthtml_workflow_session_management.models import (
    EnrichedSessionSummary,
    SessionEnricher,
    LabelGenerator,
)
from ..utils import default_label

# %% ../../nbs/services/management.ipynb #f94779bb
DEBUG_SESSION_SERVICE = False # Enable for verbose session service logging

# %% ../../nbs/services/management.ipynb #6ffa883e
class SessionManagementService:
    """Service wrapping cjm-workflow-state for session listing and lifecycle operations."""
    
    def __init__(
        self,
        state_store:SQLiteWorkflowStateStore, # The workflow state store to manage sessions in
        flow_id:str, # Workflow identifier this service is scoped to
        enricher:Optional[SessionEnricher]=None, # Optional host callback that enriches list display
        label_generator:Optional[LabelGenerator]=None, # Optional host callback for default labels
    ):
        """Initialize with a state store, flow ID, and optional host callbacks."""
        self._store = state_store
        self._flow_id = flow_id
        self._enricher = enricher
        self._label_generator = label_generator
    
    @property
    def flow_id(self) -> str: # The flow ID this service manages
        """The workflow identifier this service is scoped to."""
        return self._flow_id
    
    def _resolve_label(
        self,
        summary:SessionSummary, # Raw session metadata
        state_json:Dict[str, Any] # Full state blob for label generator input
    ) -> str: # Resolved display label
        """Resolve the display label: stored label > host generator > default."""
        if summary.label:
            return summary.label
        if self._label_generator is not None:
            try:
                return self._label_generator(summary, state_json)
            except Exception as e:
                if DEBUG_SESSION_SERVICE:
                    print(f"[SessionManagementService] label_generator raised: {e}")
        return default_label(summary.created_at)
    
    def _enrich(
        self,
        state_json:Dict[str, Any] # Full state blob for enricher input
    ) -> Dict[str, str]: # Enricher fields, empty dict if no enricher or on error
        """Run the host enricher against a state blob, returning an empty dict on any failure."""
        if self._enricher is None:
            return {}
        try:
            result = self._enricher(state_json)
            # Coerce all values to strings defensively.
            return {k: str(v) for k, v in result.items()}
        except Exception as e:
            if DEBUG_SESSION_SERVICE:
                print(f"[SessionManagementService] enricher raised: {e}")
            return {}
    
    def _to_enriched(
        self,
        summary:SessionSummary # Raw session metadata
    ) -> EnrichedSessionSummary: # Summary + label + enricher fields
        """Load the session's state blob and combine it with label resolution + enrichment."""
        state_json = self._store.get_state(self._flow_id, summary.session_id)
        return EnrichedSessionSummary(
            summary=summary,
            resolved_label=self._resolve_label(summary, state_json),
            enriched_fields=self._enrich(state_json),
        )

# %% ../../nbs/services/management.ipynb #e2f98642
@patch
def list_sessions(
    self:SessionManagementService,
    order_by:str="updated_at", # Sort column: "updated_at", "created_at", or "label"
    descending:bool=True # Sort direction
) -> List[EnrichedSessionSummary]: # All sessions with labels resolved and enricher applied
    """List all sessions for the managed flow with display enrichment applied."""
    summaries = self._store.list_sessions(self._flow_id, order_by=order_by, descending=descending)
    if DEBUG_SESSION_SERVICE:
        print(f"[SessionManagementService] list_sessions: {len(summaries)} sessions for flow={self._flow_id}")
    return [self._to_enriched(s) for s in summaries]

# %% ../../nbs/services/management.ipynb #cf23820c
@patch
def get_session(
    self:SessionManagementService,
    session_id:str # Session identifier
) -> Optional[EnrichedSessionSummary]: # Enriched session, or None if not found
    """Fetch a single enriched session summary by ID."""
    summary = self._store.get_session_summary(self._flow_id, session_id)
    if summary is None:
        return None
    return self._to_enriched(summary)

@patch
def session_exists(
    self:SessionManagementService,
    session_id:str # Session identifier
) -> bool: # True if a row exists
    """Check whether a session exists in the managed flow."""
    return self._store.session_exists(self._flow_id, session_id)

# %% ../../nbs/services/management.ipynb #ef1a09f5
@patch
def create_session(
    self:SessionManagementService,
    label:Optional[str]=None # Optional human-readable label for the new session
) -> str: # The new session_id (auto-generated UUID4)
    """Create a new empty session and return its session_id."""
    session_id = self._store.create_session(self._flow_id, label=label)
    if DEBUG_SESSION_SERVICE:
        print(f"[SessionManagementService] created session {session_id[:8]}... in flow={self._flow_id}")
    return session_id

# %% ../../nbs/services/management.ipynb #732eb309
@patch
def rename_session(
    self:SessionManagementService,
    session_id:str, # Session identifier
    label:Optional[str] # New label, or None to clear
) -> None:
    """Update a session's label. No-op if the session does not exist."""
    self._store.set_session_label(self._flow_id, session_id, label)
    if DEBUG_SESSION_SERVICE:
        print(f"[SessionManagementService] renamed {session_id[:8]}... to {label!r}")

@patch
def delete_session(
    self:SessionManagementService,
    session_id:str # Session identifier
) -> None:
    """Delete a session row. Idempotent."""
    self._store.delete_session(self._flow_id, session_id)
    if DEBUG_SESSION_SERVICE:
        print(f"[SessionManagementService] deleted {session_id[:8]}...")
