"""Top-level router assembly for the session management library."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/routes/init.ipynb.

# %% auto #0
__all__ = ['init_session_manager_routers']

# %% ../../nbs/routes/init.ipynb #4bea5890
from typing import Any, Callable, Dict, List, Optional, Tuple

from fasthtml.common import Script
from cjm_fasthtml_interactions.core.state_store import get_session_id

from cjm_fasthtml_virtual_collection.core.models import (
    VirtualCollectionConfig, VirtualCollectionState,
)
from cjm_fasthtml_virtual_collection.core.html_ids import VirtualCollectionHtmlIds
from cjm_fasthtml_virtual_collection.core.button_ids import VirtualCollectionButtonIds
from cjm_fasthtml_virtual_collection.routes.router import init_virtual_collection_router
from cjm_fasthtml_virtual_collection.routes.handlers import build_items_changed_response
from cjm_fasthtml_virtual_collection.js.auto_fit import auto_fit_callback_name

from cjm_fasthtml_workflow_session_management.models import (
    SessionManagementUrls, SessionManagementResult, ColumnSpec,
)
from ..html_ids import SessionManagerHtmlIds
from ..services.management import SessionManagementService
from cjm_fasthtml_workflow_session_management.components.session_list import (
    build_session_columns, create_session_cell_renderer, render_session_list,
)
from cjm_fasthtml_workflow_session_management.components.page_renderer import (
    render_session_manager_page,
)
from .sessions import init_session_router
from cjm_fasthtml_interactions.core.state_store import set_session_id

# %% ../../nbs/routes/init.ipynb #48d84c00
def init_session_manager_routers(
    service:SessionManagementService, # Service for session CRUD
    workflow_url:str, # URL to redirect to on resume (e.g., the workflow root)
    prefix:str="/manage/sessions", # Base prefix for all session management routes
    column_specs:Optional[List[ColumnSpec]]=None, # Host enricher column specs
    get_step_title:Optional[Callable[[str], str]]=None, # Optional step ID -> human title mapper
    page_title:str="Sessions", # Page header title
    page_icon:str="layers", # Lucide icon for the page header
    tab_entries:Optional[List[Tuple[str, str, str, str]]]=None, # Cross-management tab entries
) -> SessionManagementResult: # Assembled result with routers, urls, and render callables
    """Initialize all session management routers with virtual collection integration."""
    # --- URL bundle (populated after route registration) ---
    urls = SessionManagementUrls(
        management_page="", list_sessions="", session_detail="",
        create_session="", delete_session="", rename_session="", resume_session="",
    )
    
    # --- Shared mutable state ---
    _items:List[Any] = []
    # Holds the current active session ID so the cell renderer can draw the "Active" badge
    # without needing the request. Updated in _refresh_items from the latest HTTP session.
    _active_ref = {"id": ""}
    
    def _get_active_id() -> str:
        return _active_ref["id"]
    
    # --- VC configuration ---
    vc_config = VirtualCollectionConfig(
        prefix=SessionManagerHtmlIds.VC_PREFIX,
        columns=build_session_columns(column_specs),
    )
    vc_state = VirtualCollectionState(visible_rows=1, cursor_index=-1)
    vc_ids = VirtualCollectionHtmlIds(prefix=vc_config.prefix)
    vc_btn_ids = VirtualCollectionButtonIds(prefix=vc_config.prefix)
    _refit = auto_fit_callback_name(vc_config)
    
    # --- Cell renderer (built once; URLs are populated after route registration but
    # the renderer holds `urls` by reference, so it picks up the final values at call time). ---
    render_cell = create_session_cell_renderer(
        urls=urls,
        get_active_session_id=_get_active_id,
        get_step_title=get_step_title,
    )
    
    # --- Core callbacks ---
    def _refresh_items(request=None):
        """Reload sessions from the service and update the active session pointer."""
        _items[:] = service.list_sessions()
        vc_state.total_items = len(_items)
        vc_state.window_start = 0
        vc_state.cursor_index = 0 if _items else -1
        if request is not None:
            try:
                _active_ref["id"] = get_session_id(request.session)
            except Exception:
                _active_ref["id"] = ""
    
    def _refresh_items_oob(request=None):
        """Reload sessions and return OOB tuple for HTMX."""
        _refresh_items(request=request)
        return build_items_changed_response(
            _items, vc_state, vc_config, vc_ids, render_cell,
            focus_url=vc_urls.focus_row, refit_callback=_refit,
        )
    
    # Request-less variant for contexts where we don't have one (tests, stubs).
    def _refresh_items_noreq():
        _refresh_items(request=None)
    
    def _refresh_items_oob_noreq():
        return _refresh_items_oob(request=None)
    
    def _sort_callback(items_list, column_key, ascending):
        """Re-fetch sorted items from the service rather than sorting in place."""
        if column_key == "label":
            order_by = "label"
        elif column_key == "status":
            # Sorting by step maps to sorting by updated_at — close enough for ordering
            # sessions within the same step grouping naturally.
            order_by = "updated_at"
        elif column_key == "updated":
            order_by = "updated_at"
        else:
            order_by = "updated_at"
        items_list[:] = service.list_sessions(order_by=order_by, descending=not ascending)
    
    # --- VC router ---
    vc_router, vc_urls = init_virtual_collection_router(
        config=vc_config,
        state_getter=lambda: vc_state,
        state_setter=lambda s: None,
        get_items=lambda: _items,
        render_cell=render_cell,
        sort_callback=_sort_callback,
        route_prefix=f"{prefix}/vc",
    )
    
    # --- Render closures ---
    def _render_list():
        return render_session_list(
            items=_items,
            vc_config=vc_config,
            vc_state=vc_state,
            vc_ids=vc_ids,
            vc_btn_ids=vc_btn_ids,
            vc_urls=vc_urls,
            mgmt_urls=urls,
            render_cell=render_cell,
        )
    
    def _render_page():
        return render_session_manager_page(
            urls=urls,
            render_list_fn=_render_list,
            title=page_title,
            icon_name=page_icon,
            tab_entries=tab_entries,
            active_tab="sessions",
        )
    
    # --- Session router ---
    sess_router, sess_routes = init_session_router(
        service=service,
        prefix=prefix,
        urls=urls,
        workflow_url=workflow_url,
        refresh_items=_refresh_items_noreq,
        refresh_items_oob=_refresh_items_oob_noreq,
        render_page=_render_page,
        render_list=_render_list,
    )
    
    # --- Populate URL bundle from registered routes ---
    urls.management_page = sess_routes["management_page"].to()
    urls.list_sessions = sess_routes["list_sessions"].to()
    urls.create_session = sess_routes["create_session"].to()
    urls.delete_session = sess_routes["delete_session"].to()
    urls.rename_session = sess_routes["rename_session"].to()
    urls.resume_session = sess_routes["resume_session"].to()
    # session_detail is reserved for a future detail view.
    
    # --- Host-facing resume helper ---
    def _resume_session(sess:Any, session_id:str) -> None:
        """Set the active workflow session ID in the host HTTP session."""
        set_session_id(sess, session_id)
    
    return SessionManagementResult(
        routers=[sess_router, vc_router],
        urls=urls,
        routes=sess_routes,
        render_page=_render_page,
        render_list=_render_list,
        refresh_items=_refresh_items_noreq,
        resume_session=_resume_session,
    )
