"""Session management route handlers — list, create, delete, rename, and resume."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/routes/sessions.ipynb.

# %% auto #0
__all__ = ['DEBUG_SESSION_ROUTES', 'init_session_router']

# %% ../../nbs/routes/sessions.ipynb #5559deaf
from typing import Callable, Dict, Tuple

from fasthtml.common import APIRouter
from starlette.responses import Response

from cjm_fasthtml_interactions.core.state_store import set_session_id, get_session_id

from ..models import SessionManagementUrls
from ..services.management import SessionManagementService

# %% ../../nbs/routes/sessions.ipynb #ab20f627
DEBUG_SESSION_ROUTES = False # Enable for verbose session route logging

# %% ../../nbs/routes/sessions.ipynb #5b7bc698
def init_session_router(
    service:SessionManagementService, # Service for session CRUD
    prefix:str, # Route prefix (e.g., "/manage/sessions")
    urls:SessionManagementUrls, # URL bundle (populated by caller after init)
    workflow_url:str, # Where to redirect after resume
    refresh_items:Callable, # (request=None) -> reload items from service
    refresh_items_oob:Callable, # (request=None) -> refresh + OOB tuple for HTMX response
    render_page:Callable, # () -> full session manager page
    render_list:Callable, # () -> session list component
) -> Tuple[APIRouter, Dict[str, Callable]]: # (router, routes dict)
    """Initialize session management routes (list, create, delete, rename, resume)."""
    router = APIRouter(prefix=prefix)
    routes:Dict[str, Callable] = {}
    
    @router
    async def management_page(request):
        """Return the full session manager page."""
        if DEBUG_SESSION_ROUTES:
            print("[ROUTES] management_page called")
        refresh_items(request=request)
        return render_page()
    routes["management_page"] = management_page
    
    @router
    async def list_sessions(request):
        """Return just the session list fragment."""
        if DEBUG_SESSION_ROUTES:
            print("[ROUTES] list_sessions called")
        refresh_items(request=request)
        return render_list()
    routes["list_sessions"] = list_sessions
    
    @router.post
    async def create_session(request):
        """Mint a new session, set it active, and return the refreshed list."""
        sess = request.session
        new_id = service.create_session()
        set_session_id(sess, new_id)
        if DEBUG_SESSION_ROUTES:
            print(f"[ROUTES] create_session -> {new_id[:8]}...")
        return refresh_items_oob(request=request)
    routes["create_session"] = create_session
    
    @router.post
    async def delete_session(request):
        """Delete a session and return the refreshed list OOB."""
        form_data = await request.form()
        session_id = form_data.get("session_id", "")
        if DEBUG_SESSION_ROUTES:
            print(f"[ROUTES] delete_session: {session_id[:8] if session_id else '<none>'}...")
        if session_id:
            service.delete_session(session_id)
            # If the active session was deleted, clear the pointer so the next visit mints a fresh one.
            sess = request.session
            if get_session_id(sess) == session_id:
                # Pick the most recently updated remaining session, or mint a new one.
                remaining = service.list_sessions()
                if remaining:
                    set_session_id(sess, remaining[0].summary.session_id)
                else:
                    # No sessions left — mint a new empty one so the workflow has state to resume.
                    fresh_id = service.create_session()
                    set_session_id(sess, fresh_id)
        return refresh_items_oob(request=request)
    routes["delete_session"] = delete_session
    
    @router.post
    async def rename_session(request):
        """Rename a session and return the refreshed list OOB."""
        form_data = await request.form()
        session_id = form_data.get("session_id", "")
        label = form_data.get("label", "") or None  # empty string → clear
        if DEBUG_SESSION_ROUTES:
            print(f"[ROUTES] rename_session: {session_id[:8] if session_id else '<none>'}... -> {label!r}")
        if session_id:
            service.rename_session(session_id, label)
        return refresh_items_oob(request=request)
    routes["rename_session"] = rename_session
    
    @router.post
    async def resume_session(request):
        """Set the session active and redirect the browser to the workflow URL."""
        form_data = await request.form()
        session_id = form_data.get("session_id", "")
        if DEBUG_SESSION_ROUTES:
            print(f"[ROUTES] resume_session: {session_id[:8] if session_id else '<none>'}... -> {workflow_url}")
        if session_id and service.session_exists(session_id):
            set_session_id(request.session, session_id)
        # HX-Redirect tells HTMX to trigger a full-page navigation.
        return Response(status_code=204, headers={"HX-Redirect": workflow_url})
    routes["resume_session"] = resume_session
    
    return router, routes
